window.UA_TEAM_PROFILES = [
  {
    id: 'paid-social',
    code: 'UA-01',
    name: '优化师 01',
    role: 'Paid Social Lead',
    status: '真实姓名与履历待录入',
    photo: '',
    summary: '适合接手 Meta 与 TikTok 的规模扩量、素材衰退和新客质量问题。重点不是频繁调整账户，而是把商业目标翻译成算法能够学习的价值信号。',
    channels: ['Meta Ads', 'TikTok Ads'],
    products: ['DTC 电商', '订阅 App'],
    markets: ['待填写真实市场'],
    experience: '待填写',
    strengths: ['边际 CAC 与新客贡献利润控制', '素材母题、变量与疲劳监测', 'Pixel、CAPI 与 Events API 信号校准'],
    fit: ['花费能上升，但新客利润没有同步增长', '账户依赖少数爆款，素材一衰退就掉量', '平台 ROAS 与业务后台长期无法对账'],
    firstWeek: ['确认新客、收入、毛利和退款口径', '按市场、素材母题和用户 Cohort 拆解边际效率', '定义保留、修复、停止与扩量清单'],
    operatingView: '先确认平台正在奖励什么用户，再决定预算应该增加还是收回。',
  },
  {
    id: 'search-growth',
    code: 'UA-02',
    name: '优化师 02',
    role: 'Search Growth Lead',
    status: '真实姓名与履历待录入',
    photo: '',
    summary: '适合接手 Google Ads 搜索意图、Performance Max 和价值出价。核心任务是把高价值需求从品牌流量、泛词和低质量转化中分离出来。',
    channels: ['Google Search', 'Performance Max', 'YouTube'],
    products: ['AI / SaaS', 'DTC 电商'],
    markets: ['待填写真实市场'],
    experience: '待填写',
    strengths: ['搜索词商业意图分层', 'Feed、价值规则与智能出价', 'CRM 离线转化与 Pipeline Value 回传'],
    fit: ['CPA 看似稳定，但成交和收入质量持续走低', 'PMax 结果被品牌词或再营销重复记账', '线索很多，销售团队却认为没有有效客户'],
    firstWeek: ['审查搜索词、品牌流量与转化动作', '将广告转化映射到 MQL、SQL、成交或真实订单价值', '重排关键词、Feed、地域和预算边界'],
    operatingView: '搜索广告不是购买点击，而是在最接近决策的时刻购买高价值意图。',
  },
  {
    id: 'app-growth',
    code: 'UA-03',
    name: '优化师 03',
    role: 'App Growth Lead',
    status: '真实姓名与履历待录入',
    photo: '',
    summary: '适合接手订阅、工具和内容 App 的从 0 到 1 与跨市场扩量。把 Install、Trial、Pay、Renewal 串成可优化的价值阶梯。',
    channels: ['Meta App', 'Google App', 'TikTok App'],
    products: ['订阅 App', '移动工具'],
    markets: ['待填写真实市场'],
    experience: '待填写',
    strengths: ['MMP、SKAN 与服务端事件设计', '国家与订阅周期 Cohort 分析', '预测 LTV、回收周期与预算迁移'],
    fit: ['CPI 很低，但付费率和续费率不稳定', 'SKAN、MMP 与业务后台给出不同答案', '新市场冷启动后无法跨过学习期'],
    firstWeek: ['核对事件定义、去重和收入回传', '按国家、版本和订阅周期建立质量 Cohort', '确定冷启动信号、迁移门槛和止损规则'],
    operatingView: '安装只是一次设备事件。真正值得购买的是未来会产生收入的用户。',
  },
  {
    id: 'creative-growth',
    code: 'UA-04',
    name: '优化师 04',
    role: 'Creative Growth Strategist',
    status: '真实姓名与履历待录入',
    photo: '',
    summary: '适合接手素材供给不足、爆款不可复制和本地化失效的问题。把创意从交稿流程改造成能够持续学习的增长实验。',
    channels: ['Meta Creative', 'TikTok Creative', 'YouTube Creative'],
    products: ['App', '电商', 'AI / SaaS'],
    markets: ['待填写真实市场'],
    experience: '待填写',
    strengths: ['用户痛点、承诺与证据拆解', 'Hook、叙事和形式变量矩阵', '素材疲劳、迭代速度与本地化质量'],
    fit: ['团队在大量产素材，却不知道为什么有效', '单一爆款承担大部分花费，迭代接不上', '翻译完成了，本地市场仍然不买单'],
    firstWeek: ['复盘胜出和失败素材的共同变量', '建立人群 × 痛点 × 承诺 × 证据实验矩阵', '给出下一轮脚本、数量和判断标准'],
    operatingView: '素材产量不是目标。每一轮创意都必须让团队多知道一件关于用户的事。',
  },
]
